FROM node:12.21.0-alpine3.10

COPY ./package.json /app/package.json
COPY ./server.js /app/server.js
COPY ./client/redis-client.js /app/client/redis-client.js

WORKDIR /app

RUN npm install

EXPOSE 8080

CMD npm start
