version: "3.9"
services:
  redis:
    image: redis
    expose:
    - 6379
    container_name: redis_cache
    volumes:
    - /tmp:/data
  server:
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
    - "3000:3000"
    environment:
    - PORT=3000
    - REDIS_URL=redis://redis_cache
