name: 'Docker Build and Push'
description: 'Build and pushes a docker image to dockerhub'
inputs:
  version-major-minor: 
    description: "version major minor number"
    required: false
    default: '0.0'
  repo:
    description: "repo name"
    required: true
  dockerHubLogin:
    description: "docker hub login"
    required: true
  dockerHubPassword:
    description: "docker hub password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      id: docker-login
      run: |
        docker login -u "${{ inputs.dockerHubLogin }}" -p "${{ inputs.dockerHubPassword }}"
    - name: Build, tag, and push image to Docker Hub
      shell: bash
      id: build-image
      run: |
        docker build -t ${{ inputs.dockerHubLogin }}/${{ inputs.repo }}:${{ inputs.version-major-minor }}.${{ github.run_number }} ./simple-app/
        docker push  ${{ inputs.dockerHubLogin }}/${{ inputs.repo }}:${{ inputs.version-major-minor }}.${{ github.run_number }}
