name: 'Set Semantic Version'
description: 'Set semantic version for pipeline'
inputs:
  version-major-minor: 
    description: "version major.minor"
    required: true
  release-branch-name:
    description: "branch name to generate a new version"
    required: false
    default: "main"
output:
  version:
    description: "Pipeline version"
    

runs:
  using: "composite"
  steps:
    - name: Set semantic version
      shell: bash
      id: set-semantic-version
      run: |
        
        if [ "${{ github.ref }}" == "refs/heads/${{ inputs.release-branch-name }}" ]; then
          echo '::set-output name=version::${{ inputs.version-major-minor }}.${{ github.run_number }}'
        else
          hash=$(git rev-parse --short HEAD)
          echo '::set-output name=version::${{ inputs.version-major-minor }}.${{ github.run_number }}-$hash'
        fi
