on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Push to Docker Hub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Docker Build and Push'
      uses: argeualcantara/docker-practice-devops-group/.github/actions/docker-build-push.yml@main
      with:
        repo: docker-simple-service
        version-major-minor: '1.0'
