on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Push to Docker Hub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      id: docker-login
      run: |
        docker login -u "${{ secrets.DOCKER_HUB_USER }}" -p "${{ secrets.DOCKER_HUB_PASS }}"

    - name: Build, tag, and push image to Docker Hub
      id: build-image
      run: |
        docker build -t argeualcantara/docker-simple-service:1.0.${{ github.run_number }} ./simple-app/
        docker push  argeualcantara/docker-simple-service:1.0.${{ github.run_number }}
