on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Push to Docker Hub

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: argeualcantara/actions/semantic-version@v1.0.7
      id: semantic-version
      with:
        version-major-minor: '1.0'

    - uses: argeualcantara/actions/docker-build-push@v1.0.7
      id: docker-login-build-push
      with:
        repo: docker-simple-service
        version: ${{ steps.semantic-version.outputs.version }}
        dockerHubLogin: argeualcantara
        dockerHubPassword: ${{ secrets.DOCKER_HUB_PASS }}
        push: ${{ github.ref == 'refs/heads/main' }}
        context: ./simple-app/
