on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Push to Docker Hub

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Actions
      uses: actions/checkout@v2
      with:
        repository: argeualcantara/actions
        ref: refs/tags/v1.0.6

    - uses: argeualcantara/actions/seantic-version@v1.0.6
      with:
        version-major-minor: '1.0'
    - uses: argeualcantara/actions/docker-build-push@v1.0.6
      with:
        repo: docker-simple-service
        version-major-minor: ${{ steps.set-semantic-version.outputs.version }}
        dockerHubLogin: argeualcantara
        dockerHubPassword: ${{ secrets.DOCKER_HUB_PASS }}
        push: ${{ github.ref == 'refs/heads/main' }}
        context: ./simple-app/
